dist: xenial
language: python
cache: pip

python:
  - 2.7
  - 3.4
  - 3.5

matrix:
  include:
    - python: 3.6
      script: tox -e py36
    - python: 3.7
      script: tox -e py37
    - python: 3.8
      script: tox -e py38

install:
  - pip install tox codecov

script:
  - tox -e py

after_script:
  - codecov
