dist: xenial
language: python
cache: pip

env:
  global:
    TOXENV: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.8
      name: Linting code style
      env:
        TOXENV: lint
  allow_failures:
    - python: 3.4

before_install:
  - openssl aes-256-cbc -K $encrypted_f5440da4f437_key -iv $encrypted_f5440da4f437_iv -in .travis/gcp.json.enc -out .travis/gcp.json -d
  - export GOOGLE_APPLICATION_CREDENTIALS=$(readlink -f .travis/gcp.json)

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - codecov
